#!/usr/bin/env python3
"""
make_manuscript_plots.py
========================
Generate manuscript figures (and supplementary items from revision_notes_v2.md).

Main figures
    forest_plot.png    — Figure 1: β_m per measure, hierarchical vs. no-pooling
    shrinkage_plot.png — Shrinkage toward the global mean (manuscript numbering may vary)
    ppc_plot.png       — Figure 3 style: prior + posterior predictive (two panels)

Revision / supplementary (items 6–7 in revision_notes_v2.md)
    figure_S1_trace_rhat.png — Figure S1: trace plots + R̂ distribution (uses ArviZ)
    figure_2a_ppc_pooled.png — Pooled posterior predictive check (all measures)
    figure_2b_ppc_by_measure.png — Per-measure posterior predictive checks

Most plots avoid scipy; Figure S1 uses ArviZ for trace layout and R̂ summaries.

The posterior predictive check is computed analytically from the posterior
samples stored in idata.nc — no PyMC re-run needed:
    y_rep ~ Normal(α + β·t + b0_i + b1_i·t + u0_m + u1_m·t, σ)

The prior predictive is generated by forward-sampling from the model priors.

Usage (from repo root, pymc_env activated):
    python scripts/make_manuscript_plots.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")   # non-interactive backend — safe on Windows without display
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr

import arviz as az

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from dmt_bayes.data_prep import (
    load_data,
    build_varmap,
    reshape_long,
    standardize_within_measure,
)

RESULTS = REPO / "results"
FIGURES = RESULTS / "figures"
FIGURES.mkdir(parents=True, exist_ok=True)

# ── publication-quality matplotlib defaults ────────────────────────────────────
plt.rcParams.update({
    "font.family":        "sans-serif",
    "font.size":          11,
    "axes.spines.top":    False,
    "axes.spines.right":  False,
    "axes.linewidth":     0.8,
    "xtick.major.width":  0.8,
    "ytick.major.width":  0.8,
    "figure.dpi":         150,
})

# colour palette (colour-blind friendly)
C_HIER  = "#2171b5"   # blue  — hierarchical model
C_NP    = "#cb181d"   # red   — no-pooling model
C_GRAY  = "#636363"   # mid-gray
C_LGRAY = "#bdbdbd"   # light gray
C_BAND  = "#aec7e8"   # pale blue — predictive bands


# ─────────────────────────────────────────────────────────────────────────────
# Utilities
# ─────────────────────────────────────────────────────────────────────────────

def hdi(samples: np.ndarray, prob: float = 0.94) -> tuple[float, float]:
    """
    Highest Density Interval — pure numpy, no scipy.
    For nearly Gaussian posteriors this is essentially the same as an
    equal-tailed CI; it differs only in the tails for skewed posteriors.
    """
    s = np.sort(np.ravel(samples).astype(float))
    n = len(s)
    n_in  = int(np.floor(prob * n))
    n_out = n - n_in
    if n_out == 0:
        return float(s[0]), float(s[-1])
    widths  = s[n_in:] - s[:n_out]
    lo_idx  = int(np.argmin(widths))
    return float(s[lo_idx]), float(s[lo_idx + n_in])


def gaussian_kde(data: np.ndarray, x_grid: np.ndarray, bw: float | None = None) -> np.ndarray:
    """
    Gaussian kernel density estimate evaluated on x_grid — pure numpy.
    Uses Silverman's rule for bandwidth selection.
    """
    d = np.ravel(data).astype(float)
    d = d[np.isfinite(d)]
    if len(d) < 2:
        return np.zeros_like(x_grid)
    if bw is None:
        bw = 1.06 * d.std(ddof=1) * len(d) ** (-0.2)
    bw = max(bw, 0.02)
    # (grid_pts,) kernel evaluated at each x_grid point
    z = (x_grid[:, None] - d[None, :]) / bw       # (G, N)
    kde = np.exp(-0.5 * z ** 2).sum(axis=1) / (len(d) * bw * np.sqrt(2 * np.pi))
    return kde


def open_posterior(nc_path: Path) -> xr.Dataset:
    """Open only the 'posterior' group of an ArviZ-style NetCDF file."""
    return xr.open_dataset(str(nc_path), group="posterior")


def _plot_chains_on_ax(ax, vals: np.ndarray, title: str) -> None:
    """Trace-style line plots: vals shape (chain, draw) or (chain, draw, K)."""
    vals = np.asarray(vals, dtype=float)
    if vals.ndim == 2:
        for c in range(vals.shape[0]):
            ax.plot(vals[c], lw=0.45, alpha=0.75)
    elif vals.ndim == 3:
        n_last = vals.shape[-1]
        cmap = plt.cm.tab10(np.linspace(0, 1, min(n_last, 10)))
        for k in range(n_last):
            for c in range(vals.shape[0]):
                ax.plot(vals[c, :, k], lw=0.4, alpha=0.55, color=cmap[k % 10])
    else:
        ax.text(0.5, 0.5, f"(unexpected ndim={vals.ndim})", ha="center", va="center", transform=ax.transAxes)
    ax.set_title(title, fontsize=9)
    if vals.ndim >= 2:
        ax.set_xlim(0, max(vals.shape[1] - 1, 1))
    ax.tick_params(labelsize=7)


def prepare_data():
    """Load + reshape + standardize data; return arrays and metadata."""
    df       = load_data(str(REPO / "data" / "scales_results.csv"))
    varmap   = build_varmap(df)
    dat_long, measure_order = reshape_long(df, varmap)
    dat_long, _             = standardize_within_measure(dat_long)
    dat_long["time_c"]      = np.where(dat_long["time"] == "pre", -0.5, 0.5)

    id_cat   = pd.Categorical(dat_long["id"])
    meas_cat = dat_long["measure"].cat.codes.values

    y        = dat_long["z"].values.astype(float)
    time_c   = dat_long["time_c"].values.astype(float)
    id_idx   = id_cat.codes.astype(int)
    meas_idx = meas_cat.astype(int)
    n_id     = int(id_cat.categories.size)
    n_meas   = len(measure_order)

    return y, time_c, id_idx, meas_idx, n_id, n_meas, measure_order


def _posterior_predictive_kdes(
    y_obs: np.ndarray,
    time_c: np.ndarray,
    id_idx: np.ndarray,
    meas_idx: np.ndarray,
    alpha_all: np.ndarray,
    beta_all: np.ndarray,
    RE_flat: np.ndarray,
    u0_flat: np.ndarray,
    u1_flat: np.ndarray,
    sigma_all: np.ndarray,
    s_idx: np.ndarray,
    x_grid: np.ndarray,
    RNG: np.random.Generator,
) -> np.ndarray:
    """
    For each posterior draw index in s_idx, simulate y_rep and return KDE curves
    stacked as (len(s_idx), len(x_grid)).
    """
    n_rep = len(s_idx)
    post_kdes = np.empty((n_rep, len(x_grid)))
    for k, s in enumerate(s_idx):
        mu = (
            alpha_all[s]
            + beta_all[s] * time_c
            + RE_flat[s, id_idx, 0]
            + RE_flat[s, id_idx, 1] * time_c
            + u0_flat[s, meas_idx]
            + u1_flat[s, meas_idx] * time_c
        )
        y_rep = RNG.normal(mu, sigma_all[s]).astype(float)
        post_kdes[k] = gaussian_kde(y_rep, x_grid)
    return post_kdes


# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 1 — Forest plot
# ─────────────────────────────────────────────────────────────────────────────

def plot_forest():
    """
    Horizontal forest plot of the measure-specific time effects β_m.

    Each measure occupies one row. Blue (hierarchical, partial pooling) and
    red (no-pooling) estimates are vertically offset within the row.
    The thick segment is the 50 % HDI; the thin line is the 94 % HDI; the
    filled symbol is the posterior mean.

    If idata_nopooling.nc is not yet available, the no-pooling column falls
    back to the raw sample-mean difference (equivalent to a frequentist
    paired-t effect size in standardised units).
    """
    print("  [Figure 1] Forest plot …")

    # ── Hierarchical β_m from idata.nc ────────────────────────────────────────
    ds_h  = open_posterior(RESULTS / "idata.nc")
    bm_h  = ds_h["beta_m_by_measure"].values          # (chain, draw, measure)
    meas_coords = list(ds_h.coords["measure"].values)
    ds_h.close()

    n_meas  = len(meas_coords)
    flat_h  = bm_h.reshape(-1, n_meas)                # (S, M)
    h_mean  = flat_h.mean(0)
    h94     = np.array([hdi(flat_h[:, m], 0.94) for m in range(n_meas)])
    h50     = np.array([hdi(flat_h[:, m], 0.50) for m in range(n_meas)])

    # ── No-pooling β_m ────────────────────────────────────────────────────────
    nopool_nc = RESULTS / "idata_nopooling.nc"
    if nopool_nc.exists():
        ds_np   = open_posterior(nopool_nc)
        bm_np   = ds_np["beta_m"].values.reshape(-1, n_meas)
        ds_np.close()
        np_mean  = bm_np.mean(0)
        np94     = np.array([hdi(bm_np[:, m], 0.94) for m in range(n_meas)])
        np50     = np.array([hdi(bm_np[:, m], 0.50) for m in range(n_meas)])
        np_label = "No-pooling"
    else:
        # Fallback: raw standardised pre-post difference per measure
        y, time_c, id_idx, meas_idx, n_id, _, _ = prepare_data()
        np_mean  = np.zeros(n_meas)
        np_se    = np.zeros(n_meas)
        for m in range(n_meas):
            mask  = meas_idx == m
            ym, tm = y[mask], time_c[mask]
            diffs  = ym[tm > 0] - ym[tm < 0]
            np_mean[m] = diffs.mean()
            np_se[m]   = diffs.std(ddof=1) / np.sqrt(len(diffs))
        # t_{n−1} ≈ 34 df: 94 % ↔ ±2.10 SE, 50 % ↔ ±0.68 SE
        np94 = np.column_stack([np_mean - 2.10 * np_se, np_mean + 2.10 * np_se])
        np50 = np.column_stack([np_mean - 0.68 * np_se, np_mean + 0.68 * np_se])
        np_label = "No-pooling (raw)"

    # ── Draw ──────────────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(8.0, 6.4))
    OFFSET = 0.18  # vertical jitter between the two model estimates per row

    # ROPE band (drawn first so it sits behind the estimates)
    ax.axvspan(ROPE_LO, ROPE_HI, color="#d9d9d9", alpha=0.55, zorder=0,
               label=f"ROPE  [{ROPE_LO}, {ROPE_HI}] SD")

    for m in range(n_meas):
        row  = n_meas - 1 - m          # top-to-bottom layout
        y_h  = row + OFFSET
        y_np = row - OFFSET

        # ── hierarchical ──────────────────────────────────────────────────
        ax.plot(h94[m],  [y_h,  y_h],  color=C_HIER, lw=1.2, zorder=2)
        ax.plot(h50[m],  [y_h,  y_h],  color=C_HIER, lw=3.8, zorder=3,
                solid_capstyle="round")
        ax.scatter(h_mean[m], y_h, color=C_HIER, s=55, zorder=4)

        # ── no-pooling ────────────────────────────────────────────────────
        ax.plot(np94[m],  [y_np, y_np], color=C_NP,   lw=1.2, zorder=2)
        ax.plot(np50[m],  [y_np, y_np], color=C_NP,   lw=3.8, zorder=3,
                solid_capstyle="round")
        ax.scatter(np_mean[m], y_np, color=C_NP, marker="D", s=40, zorder=4)

    ax.axvline(0, color=C_GRAY, lw=0.9, linestyle="--", zorder=1)

    # y-axis measure labels
    ax.set_yticks(np.arange(n_meas))
    ax.set_yticklabels(list(reversed(meas_coords)), fontsize=10)
    ax.set_ylim(-0.65, n_meas - 0.35)

    # Legend placed below the axes so it never overlaps the intervals
    legend_handles = [
        mpatches.Patch(color=C_HIER, label="Hierarchical (partial pooling)"),
        mpatches.Patch(color="#d9d9d9", alpha=0.75,
                       label=f"ROPE  [{ROPE_LO}, {ROPE_HI}] SD"),
        mpatches.Patch(color=C_NP,   label=np_label),
        plt.Line2D([0], [0], lw=1.2, color=C_GRAY, linestyle="--", label="Zero reference"),
        plt.Line2D([0], [0], lw=3.8, color=C_GRAY, label="Thick bar = 50 % HDI",
                   solid_capstyle="round"),
        plt.Line2D([0], [0], lw=1.2, color=C_GRAY, label="Thin line = 94 % HDI"),
    ]
    fig.legend(handles=legend_handles, loc="lower center",
               bbox_to_anchor=(0.5, -0.02), ncol=3,
               fontsize=9, framealpha=0.9, edgecolor=C_LGRAY)

    ax.set_xlabel(r"Standardized Pre-to-Post Change ($\beta_m$, SD units)", fontsize=11)
    ax.set_ylabel("Outcome Measure", fontsize=11)
    ax.set_title(
        "Measure-Specific Time Effects:\nHierarchical (Partial Pooling) vs. No-Pooling",
        fontsize=11, pad=10
    )

    fig.tight_layout()
    fig.subplots_adjust(bottom=0.15)   # reserve space below axes for the legend
    out = FIGURES / "forest_plot.png"
    fig.savefig(str(out), dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"    → {out}")


# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 2 — Shrinkage plot
# ─────────────────────────────────────────────────────────────────────────────

def plot_shrinkage():
    """
    Shrinkage plot: no-pooling estimate (x) vs. hierarchical estimate (y).

    Each point is one outcome measure, labelled by name.
    A dashed diagonal y = x marks zero shrinkage.
    A dotted horizontal line shows the global posterior mean β (the target
    toward which partial pooling shrinks every measure-level estimate).
    Blue arrows run vertically from the no-pooling position on the diagonal
    to the hierarchical posterior mean, visually showing how much each
    measure is regularised toward the global mean.
    """
    print("  [Figure 2] Shrinkage plot …")

    # ── Hierarchical ─────────────────────────────────────────────────────────
    ds_h       = open_posterior(RESULTS / "idata.nc")
    bm_h       = ds_h["beta_m_by_measure"].values     # (chain, draw, measure)
    beta_g     = ds_h["beta_time"].values.ravel()     # global time effect
    meas_coords = list(ds_h.coords["measure"].values)
    ds_h.close()

    n_meas    = len(meas_coords)
    flat_h    = bm_h.reshape(-1, n_meas)
    h_mean    = flat_h.mean(0)
    g_mean    = float(beta_g.mean())

    # ── No-pooling ────────────────────────────────────────────────────────────
    nopool_nc = RESULTS / "idata_nopooling.nc"
    if nopool_nc.exists():
        ds_np     = open_posterior(nopool_nc)
        np_mean   = ds_np["beta_m"].values.reshape(-1, n_meas).mean(0)
        ds_np.close()
        np_label  = "No-pooling posterior mean"
    else:
        y, time_c, id_idx, meas_idx, n_id, _, _ = prepare_data()
        np_mean = np.zeros(n_meas)
        for m in range(n_meas):
            mask = meas_idx == m
            ym, tm = y[mask], time_c[mask]
            np_mean[m] = ym[tm > 0].mean() - ym[tm < 0].mean()
        np_label = "No-pooling (raw sample mean)"

    # ── Draw ──────────────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(6.8, 6.0))

    # Axis limits: symmetric, slightly padded
    bound = max(np.abs(np_mean).max(), np.abs(h_mean).max()) * 1.55
    bound = max(bound, 0.20)
    ax.set_xlim(-bound, bound)
    ax.set_ylim(-bound, bound)

    # Reference: y = x (no shrinkage)
    ax.plot([-bound, bound], [-bound, bound],
            color=C_LGRAY, lw=1.1, linestyle="--", zorder=1, label="$y = x$  (no shrinkage)")

    # Reference: horizontal global mean
    ax.axhline(g_mean, color=C_GRAY, lw=1.0, linestyle=":",
               zorder=1, label=f"Global posterior mean  β = {g_mean:.3f}")

    # Arrows: from (np, np) on the diagonal → (np, hier)
    for m in range(n_meas):
        shrink = h_mean[m] - np_mean[m]        # vertical distance
        if abs(shrink) > 1e-4:
            ax.annotate(
                "",
                xy=(np_mean[m], h_mean[m]),    # arrowhead
                xytext=(np_mean[m], np_mean[m]),  # tail (on diagonal)
                arrowprops=dict(
                    arrowstyle="-|>",
                    color=C_HIER,
                    lw=1.6,
                    mutation_scale=10,
                ),
                zorder=3,
            )

    # No-pooling positions on the diagonal (red diamonds)
    ax.scatter(np_mean, np_mean, color=C_NP, marker="D", s=55, zorder=4,
               label=np_label)

    # Hierarchical positions (blue circles)
    ax.scatter(np_mean, h_mean, color=C_HIER, s=60, zorder=5,
               label="Hierarchical posterior mean")

    # Point labels (offset to avoid overlap)
    for m, lbl in enumerate(meas_coords):
        ax.annotate(
            lbl,
            xy=(np_mean[m], h_mean[m]),
            xytext=(5, 4),
            textcoords="offset points",
            fontsize=8.5,
            color="#222222",
        )

    ax.set_xlabel(f"{np_label}  " + r"($\beta_m$, SD units)", fontsize=11)
    ax.set_ylabel(r"Hierarchical posterior mean  ($\beta_m$, SD units)", fontsize=11)
    ax.set_title(
        "Hierarchical Shrinkage of Measure-Specific Time Effects\n"
        "(Arrows show regularisation toward the global mean)",
        fontsize=11, pad=10
    )
    ax.legend(loc="upper left", fontsize=9, framealpha=0.9, edgecolor=C_LGRAY)

    fig.tight_layout()
    out = FIGURES / "shrinkage_plot.png"
    fig.savefig(str(out), dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"    → {out}")


# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 3 — Prior and posterior predictive checks
# ─────────────────────────────────────────────────────────────────────────────

def plot_ppc():
    """
    Two-panel figure: prior predictive check (left) and posterior predictive
    check (right).

    Each panel shows the observed standardised score distribution (bold black
    line) against 300 light KDE traces of replicated datasets y_rep, plus the
    mean replicated KDE (coloured dashed line).

    Posterior predictive is reconstructed from the posterior draws already
    stored in idata.nc using the full linear predictor:
        y_rep ~ Normal(α + β·t + RE_id_{i,0} + RE_id_{i,1}·t
                        + u0_m + u1_m·t,  σ)
    No PyMC re-run is needed.

    Prior predictive is generated by independently sampling each parameter
    from its prior and propagating through the same predictor.
    """
    print("  [Figure 3] PPC plot …")
    RNG = np.random.default_rng(42)

    # ── Observed data ─────────────────────────────────────────────────────────
    y_obs, time_c, id_idx, meas_idx, n_id, n_meas, _ = prepare_data()
    n_obs = len(y_obs)
    x_grid = np.linspace(-4.5, 4.5, 400)
    kde_obs = gaussian_kde(y_obs, x_grid)

    # ── Posterior predictive ─────────────────────────────────────────────────
    ds   = open_posterior(RESULTS / "idata.nc")
    alpha_all  = ds["alpha"].values.ravel()          # (S,)
    beta_all   = ds["beta_time"].values.ravel()      # (S,)
    RE_id_all  = ds["RE_id"].values                  # (chain, draw, id, 2)
    u0_m_all   = ds["u0_m"].values                   # (chain, draw, measure)
    u1_m_all   = ds["u1_m"].values                   # (chain, draw, measure)
    sigma_all  = ds["sigma"].values.ravel()          # (S,)
    n_chains, n_draws_per = ds["alpha"].shape
    ds.close()

    S = n_chains * n_draws_per
    RE_flat  = RE_id_all.reshape(S, n_id, 2)
    u0_flat  = u0_m_all.reshape(S, n_meas)
    u1_flat  = u1_m_all.reshape(S, n_meas)

    # Subsample to n_rep evenly-spaced draws for speed
    n_rep   = 300
    step    = max(1, S // n_rep)
    s_idx   = np.arange(0, S, step)[:n_rep]

    post_kdes = _posterior_predictive_kdes(
        y_obs,
        time_c,
        id_idx,
        meas_idx,
        alpha_all,
        beta_all,
        RE_flat,
        u0_flat,
        u1_flat,
        sigma_all,
        s_idx,
        x_grid,
        RNG,
    )

    # ── Prior predictive ─────────────────────────────────────────────────────
    # Forward-sample each parameter independently from its prior
    prior_kdes = np.empty((n_rep, len(x_grid)))
    for k in range(n_rep):
        alpha_s  = RNG.normal(0.0, 1.0)
        beta_s   = RNG.normal(0.0, 1.0)
        sigma_s  = np.abs(RNG.normal(0.0, 1.0))            # HalfNormal(1.0)
        sig_id   = np.abs(RNG.normal(0.0, 0.75, 2))        # HalfNormal(0.75) × 2
        # subject intercepts and slopes (independent; corr ignored in prior)
        b0_i     = RNG.normal(0.0, sig_id[0], n_id)
        b1_i     = RNG.normal(0.0, sig_id[1], n_id)
        # measure random effects
        sd_u0    = np.abs(RNG.normal(0.0, 0.75))
        sd_u1    = np.abs(RNG.normal(0.0, 0.75))
        u0_m_s   = RNG.normal(0.0, sd_u0, n_meas)
        u1_m_s   = RNG.normal(0.0, sd_u1, n_meas)

        mu = (
            alpha_s
            + beta_s     * time_c
            + b0_i[id_idx]
            + b1_i[id_idx] * time_c
            + u0_m_s[meas_idx]
            + u1_m_s[meas_idx] * time_c
        )
        y_rep = RNG.normal(mu, sigma_s).astype(float)
        prior_kdes[k] = gaussian_kde(y_rep, x_grid)

    # ── Draw ──────────────────────────────────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.5), sharey=True)

    for ax, kdes, mean_color, panel_title in [
        (axes[0], prior_kdes,  C_NP,   "Prior Predictive Check"),
        (axes[1], post_kdes,   C_HIER, "Posterior Predictive Check"),
    ]:
        # Individual replicated KDEs (light band)
        for k in range(n_rep):
            ax.plot(x_grid, kdes[k], color=C_BAND, alpha=0.06, lw=0.7, zorder=1)
        # Mean replicated KDE
        ax.plot(x_grid, kdes.mean(0), color=mean_color, lw=1.8,
                linestyle="--", zorder=3, label=r"Mean replicated $\hat{y}$")
        # Observed KDE
        ax.plot(x_grid, kde_obs, color="black", lw=2.2, zorder=4,
                label="Observed data")

        ax.set_xlim(-4.5, 4.5)
        ax.set_xlabel("Standardised Score (z)", fontsize=11)
        ax.set_title(panel_title, fontsize=11, pad=8)
        ax.legend(fontsize=9, framealpha=0.9, edgecolor=C_LGRAY, loc="upper right")

    axes[0].set_ylabel("Density", fontsize=11)
    fig.suptitle(
        "Predictive Checks — All Outcome Measures Combined\n"
        "(light traces = individual replicated datasets; bold = observed)",
        fontsize=10, y=1.01
    )

    fig.tight_layout()
    out = FIGURES / "ppc_plot.png"
    fig.savefig(str(out), dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"    → {out}")


# ─────────────────────────────────────────────────────────────────────────────
# FIGURE S1 — Trace plots + R̂ (Supplementary; revision_notes_v2.md item 6)
# ─────────────────────────────────────────────────────────────────────────────

def plot_figure_s1_trace_rhat():
    """
    Figure S1: trace plots for key structural / measure-level parameters and a
    histogram of Gelman--Rubin R̂ for the same set (plus u0_m, u1_m, z_u0, z_u1).

    Latent subject-level arrays (z_id, RE_id) are omitted to keep the figure readable.
    """
    print("  [Figure S1] Trace plots + " + r"$\hat{R}$ …")

    idata_path = RESULTS / "idata.nc"
    if not idata_path.exists():
        raise FileNotFoundError(f"Missing {idata_path}")

    idata = az.from_netcdf(str(idata_path))
    ds = idata.posterior

    trace_vars = [
        "alpha",
        "beta_time",
        "sigma",
        "sd_u0",
        "sd_u1",
        "sigma_id",
        "corr_id",
        "beta_m_by_measure",
    ]
    present = [v for v in trace_vars if v in ds.data_vars]

    n_trace = len(present)
    fig, axes = plt.subplots(
        n_trace + 1,
        1,
        figsize=(10, 1.65 * n_trace + 2.4),
        gridspec_kw={"height_ratios": [1.15] * n_trace + [1.0]},
    )
    if n_trace == 0:
        raise RuntimeError("No trace variables found in idata.posterior")

    axes = np.atleast_1d(axes)

    for ax, name in zip(axes[:-1], present):
        _plot_chains_on_ax(ax, ds[name].values, name)
        ax.set_ylabel("value", fontsize=8)

    summ_vars = [
        "alpha",
        "beta_time",
        "sigma",
        "sd_u0",
        "sd_u1",
        "sigma_id",
        "corr_id",
        "beta_m_by_measure",
        "u0_m",
        "u1_m",
        "z_u0",
        "z_u1",
    ]
    summ_vars = [v for v in summ_vars if v in ds.data_vars]
    summ = az.summary(idata, var_names=summ_vars, hdi_prob=0.94)
    r_hat = summ["r_hat"].values.astype(float)
    r_hat = r_hat[np.isfinite(r_hat)]

    axr = axes[-1]
    nb = min(40, max(10, len(r_hat) // 2))
    axr.hist(r_hat, bins=nb, color=C_HIER, edgecolor="white", alpha=0.9)
    axr.axvline(1.0, color="black", ls="--", lw=1)
    axr.axvline(1.01, color=C_NP, ls=":", lw=1, label="1.01 (common rule-of-thumb)")
    axr.set_xlabel(r"$\hat{R}$", fontsize=10)
    axr.set_ylabel("Count", fontsize=10)
    axr.set_title(
        r"$\hat{R}$ across monitored structural + measure-level parameters "
        r"(excludes z_id / RE_id)",
        fontsize=9,
    )
    axr.legend(fontsize=8, loc="upper right")

    fig.suptitle(
        r"Figure S1 — Convergence diagnostics (traces + $\hat{R}$)",
        fontsize=12,
        y=1.01,
    )
    fig.tight_layout()
    out = FIGURES / "figure_S1_trace_rhat.png"
    fig.savefig(str(out), dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"    → {out}")


# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 2a–2b — Pooled vs per-measure PPC (revision_notes_v2.md item 7)
# ─────────────────────────────────────────────────────────────────────────────

def plot_figure_2a_ppc_pooled():
    """
    Figure 2a: pooled posterior predictive check (all measures, all time points),
    matching the right-hand panel logic of ppc_plot.png.
    """
    print("  [Figure 2a] Pooled posterior predictive check …")
    RNG = np.random.default_rng(42)

    y_obs, time_c, id_idx, meas_idx, n_id, n_meas, _ = prepare_data()
    x_grid = np.linspace(-4.5, 4.5, 400)
    kde_obs = gaussian_kde(y_obs, x_grid)

    ds = open_posterior(RESULTS / "idata.nc")
    alpha_all = ds["alpha"].values.ravel()
    beta_all = ds["beta_time"].values.ravel()
    RE_id_all = ds["RE_id"].values
    u0_m_all = ds["u0_m"].values
    u1_m_all = ds["u1_m"].values
    sigma_all = ds["sigma"].values.ravel()
    n_chains, n_draws_per = ds["alpha"].shape
    ds.close()

    S = n_chains * n_draws_per
    RE_flat = RE_id_all.reshape(S, n_id, 2)
    u0_flat = u0_m_all.reshape(S, n_meas)
    u1_flat = u1_m_all.reshape(S, n_meas)

    n_rep = 300
    step = max(1, S // n_rep)
    s_idx = np.arange(0, S, step)[:n_rep]

    post_kdes = _posterior_predictive_kdes(
        y_obs,
        time_c,
        id_idx,
        meas_idx,
        alpha_all,
        beta_all,
        RE_flat,
        u0_flat,
        u1_flat,
        sigma_all,
        s_idx,
        x_grid,
        RNG,
    )

    fig, ax = plt.subplots(figsize=(6.2, 4.6))
    for k in range(n_rep):
        ax.plot(x_grid, post_kdes[k], color=C_BAND, alpha=0.06, lw=0.7, zorder=1)
    ax.plot(
        x_grid,
        post_kdes.mean(0),
        color=C_HIER,
        lw=1.8,
        linestyle="--",
        zorder=3,
        label=r"Mean replicated $\hat{y}$",
    )
    ax.plot(x_grid, kde_obs, color="black", lw=2.2, zorder=4, label="Observed data")
    ax.set_xlim(-4.5, 4.5)
    ax.set_xlabel("Standardised score (z)", fontsize=11)
    ax.set_ylabel("Density", fontsize=11)
    ax.set_title(
        "Figure 2a — Pooled posterior predictive check\n(all measures combined)",
        fontsize=11,
        pad=8,
    )
    ax.legend(fontsize=9, framealpha=0.9, edgecolor=C_LGRAY, loc="upper right")
    fig.tight_layout()
    out = FIGURES / "figure_2a_ppc_pooled.png"
    fig.savefig(str(out), dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"    → {out}")


def plot_figure_2b_ppc_by_measure():
    """
    Figure 2b: one posterior predictive check per outcome measure (empirical
    check of Gaussian likelihood / residual variance per scale).
    """
    print("  [Figure 2b] Per-measure posterior predictive checks …")
    RNG = np.random.default_rng(43)

    y_obs, time_c, id_idx, meas_idx, n_id, n_meas, measure_order = prepare_data()
    x_grid = np.linspace(-4.5, 4.5, 220)

    ds = open_posterior(RESULTS / "idata.nc")
    alpha_all = ds["alpha"].values.ravel()
    beta_all = ds["beta_time"].values.ravel()
    RE_id_all = ds["RE_id"].values
    u0_m_all = ds["u0_m"].values
    u1_m_all = ds["u1_m"].values
    sigma_all = ds["sigma"].values.ravel()
    n_chains, n_draws_per = ds["alpha"].shape
    ds.close()

    S = n_chains * n_draws_per
    RE_flat = RE_id_all.reshape(S, n_id, 2)
    u0_flat = u0_m_all.reshape(S, n_meas)
    u1_flat = u1_m_all.reshape(S, n_meas)

    n_rep = 200
    step = max(1, S // n_rep)
    s_idx = np.arange(0, S, step)[:n_rep]

    ncols = 3
    nrows = int(np.ceil(n_meas / ncols))
    fig, axes = plt.subplots(
        nrows,
        ncols,
        figsize=(3.4 * ncols, 2.8 * nrows),
        sharex=True,
        sharey=True,
    )
    axes_flat = np.atleast_1d(axes).ravel()

    for m in range(n_meas):
        ax = axes_flat[m]
        mask = meas_idx == m
        y_m = y_obs[mask]
        time_cm = time_c[mask]
        id_idx_m = id_idx[mask]
        meas_idx_m = meas_idx[mask]

        kde_obs_m = gaussian_kde(y_m, x_grid)
        post_kdes_m = _posterior_predictive_kdes(
            y_m,
            time_cm,
            id_idx_m,
            meas_idx_m,
            alpha_all,
            beta_all,
            RE_flat,
            u0_flat,
            u1_flat,
            sigma_all,
            s_idx,
            x_grid,
            RNG,
        )
        for k in range(len(s_idx)):
            ax.plot(x_grid, post_kdes_m[k], color=C_BAND, alpha=0.07, lw=0.55, zorder=1)
        ax.plot(
            x_grid,
            post_kdes_m.mean(0),
            color=C_HIER,
            lw=1.3,
            linestyle="--",
            zorder=3,
        )
        ax.plot(x_grid, kde_obs_m, color="black", lw=1.6, zorder=4)
        ax.set_title(str(measure_order[m]), fontsize=9)
        ax.set_xlim(-4.5, 4.5)
        ax.tick_params(labelsize=7)

    for j in range(n_meas, len(axes_flat)):
        axes_flat[j].set_visible(False)

    fig.suptitle(
        "Figure 2b — Posterior predictive checks by measure",
        fontsize=12,
        y=1.02,
    )
    fig.supxlabel("Standardised score (z)", fontsize=10, y=0.02)
    fig.supylabel("Density", fontsize=10, x=0.02)
    fig.tight_layout()
    out = FIGURES / "figure_2b_ppc_by_measure.png"
    fig.savefig(str(out), dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"    → {out}")


# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 4 — Sensitivity forest plot (prior robustness, §3.5)
# ─────────────────────────────────────────────────────────────────────────────

# Colours for the three prior specifications
C_SPEC_A = "#2171b5"   # blue   — Spec A (default)
C_SPEC_B = "#d94801"   # orange — Spec B (tighter priors, SDs halved)
C_SPEC_C = "#31a354"   # green  — Spec C (wider priors, SDs doubled)

ROPE_LO, ROPE_HI = -0.10, 0.10   # matches manuscript_analyses.py task6


def plot_figure_4_sensitivity_forest():
    """
    Figure 4: sensitivity forest plot for the prior robustness analysis (Q2).

    Each row is one outcome measure; three point-range displays are drawn
    within the row — one per prior specification (A, B, C) — vertically
    offset so they never overlap.  A shared ROPE band [−0.1, 0.1] is shown
    as a light grey rectangle.  The 94 % HDI is shown as a thin horizontal
    line; the posterior mean as a filled circle.

    Data are read from ``results/sensitivity_results.csv`` which is written
    by ``manuscript_analyses.py`` (task4_sensitivity).  The function also
    attempts to load the raw posterior draws from ``idata_spec_b.nc`` /
    ``idata_spec_c.nc`` to draw the 50 % HDI (thick bar) in the same style
    as Figure 1; if those files are absent it falls back to the CSV summaries
    only (thin line + point).
    """
    print("  [Figure 4] Sensitivity forest plot …")

    csv_path = RESULTS / "sensitivity_results.csv"
    if not csv_path.exists():
        raise FileNotFoundError(
            f"Missing {csv_path} — run manuscript_analyses.py task4 first."
        )

    df = pd.read_csv(csv_path)
    measures = df["measure"].tolist()
    n_meas = len(measures)

    # ── Posterior means and 94 % HDIs from CSV ────────────────────────────────
    specs = {
        "A": {
            "mean":   df["spec_a_mean"].values,
            "hdi_lo": df["spec_a_hdi_lo"].values,
            "hdi_hi": df["spec_a_hdi_hi"].values,
            "color":  C_SPEC_A,
            "label":  "Spec A  (default)",
            "offset": +0.22,
        },
        "B": {
            "mean":   df["spec_b_mean"].values,
            "hdi_lo": df["spec_b_hdi_lo"].values,
            "hdi_hi": df["spec_b_hdi_hi"].values,
            "color":  C_SPEC_B,
            "label":  "Spec B  (tighter: SDs × ½)",
            "offset":  0.00,
        },
        "C": {
            "mean":   df["spec_c_mean"].values,
            "hdi_lo": df["spec_c_hdi_lo"].values,
            "hdi_hi": df["spec_c_hdi_hi"].values,
            "color":  C_SPEC_C,
            "label":  "Spec C  (wider: SDs × 2)",
            "offset": -0.22,
        },
    }

    # ── Optional: 50 % HDI from raw draws ────────────────────────────────────
    spec_nc = {
        "A": RESULTS / "idata.nc",
        "B": RESULTS / "idata_spec_b.nc",
        "C": RESULTS / "idata_spec_c.nc",
    }
    for key, info in specs.items():
        nc = spec_nc[key]
        info["hdi50"] = None
        if nc.exists():
            try:
                ds = open_posterior(nc)
                # prefer beta_m_by_measure (hierarchical); fall back to beta_m
                if "beta_m_by_measure" in ds.data_vars:
                    bm = ds["beta_m_by_measure"].values.reshape(-1, n_meas)
                elif "beta_m" in ds.data_vars:
                    bm = ds["beta_m"].values.reshape(-1, n_meas)
                else:
                    bm = None
                ds.close()
                if bm is not None:
                    info["hdi50"] = np.array(
                        [hdi(bm[:, m], 0.50) for m in range(n_meas)]
                    )
            except Exception:
                pass   # silently fall back to CSV-only display

    # ── Draw ──────────────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(8.5, 6.8))

    # ROPE band (drawn first so it sits behind the estimates)
    ax.axvspan(ROPE_LO, ROPE_HI, color="#d9d9d9", alpha=0.55, zorder=0,
               label=f"ROPE  [{ROPE_LO}, {ROPE_HI}] SD")

    # Zero reference
    ax.axvline(0, color=C_GRAY, lw=0.9, linestyle="--", zorder=1)

    for m in range(n_meas):
        row = n_meas - 1 - m   # top-to-bottom layout

        for info in specs.values():
            y_pos   = row + info["offset"]
            lo, hi  = float(info["hdi_lo"][m]), float(info["hdi_hi"][m])
            mn      = float(info["mean"][m])
            col     = info["color"]

            # 94 % HDI — thin line
            ax.plot([lo, hi], [y_pos, y_pos], color=col, lw=1.2, zorder=2)

            # 50 % HDI — thick bar (if available from raw draws)
            if info["hdi50"] is not None:
                h50_lo, h50_hi = info["hdi50"][m]
                ax.plot([h50_lo, h50_hi], [y_pos, y_pos],
                        color=col, lw=3.8, zorder=3, solid_capstyle="round")

            # Posterior mean — filled circle
            ax.scatter(mn, y_pos, color=col, s=48, zorder=4)

    # y-axis measure labels
    ax.set_yticks(np.arange(n_meas))
    ax.set_yticklabels(list(reversed(measures)), fontsize=10)
    ax.set_ylim(-0.65, n_meas - 0.35)

    # Legend
    legend_handles = [
        mpatches.Patch(color=info["color"], label=info["label"])
        for info in specs.values()
    ] + [
        mpatches.Patch(color="#d9d9d9", alpha=0.75,
                       label=f"ROPE  [{ROPE_LO}, {ROPE_HI}] SD"),
        plt.Line2D([0], [0], lw=1.2, color=C_GRAY, linestyle="--",
                   label="Zero reference"),
        plt.Line2D([0], [0], lw=3.8, color=C_GRAY,
                   label="Thick bar = 50 % HDI", solid_capstyle="round"),
        plt.Line2D([0], [0], lw=1.2, color=C_GRAY,
                   label="Thin line = 94 % HDI"),
    ]
    fig.legend(handles=legend_handles, loc="lower center",
               bbox_to_anchor=(0.5, -0.02), ncol=3,
               fontsize=9, framealpha=0.9, edgecolor=C_LGRAY)

    ax.set_xlabel(
        r"Standardised Pre-to-Post Change ($\beta_m$, SD units)", fontsize=11
    )
    ax.set_ylabel("Outcome Measure", fontsize=11)
    ax.set_title(
        "Figure 4 — Prior Sensitivity: $\\beta_m$ Posteriors Across\n"
        "Three Prior Specifications (A = default, B = tighter, C = wider)",
        fontsize=11, pad=10,
    )

    fig.tight_layout()
    fig.subplots_adjust(bottom=0.18)
    out = FIGURES / "figure_4_sensitivity_forest.png"
    fig.savefig(str(out), dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"    → {out}")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 65)
    print("DMT Bayesian Hierarchical — Manuscript Plots")
    print("=" * 65)

    errors = []
    for name, fn in [
        ("forest_plot.png",                  plot_forest),
        ("shrinkage_plot.png",               plot_shrinkage),
        ("ppc_plot.png",                     plot_ppc),
        ("figure_S1_trace_rhat.png",         plot_figure_s1_trace_rhat),
        ("figure_2a_ppc_pooled.png",         plot_figure_2a_ppc_pooled),
        ("figure_2b_ppc_by_measure.png",     plot_figure_2b_ppc_by_measure),
        ("figure_4_sensitivity_forest.png",  plot_figure_4_sensitivity_forest),
    ]:
        try:
            fn()
        except Exception as exc:
            print(f"  ERROR generating {name}: {exc}")
            errors.append(name)

    print("\n" + "=" * 65)
    if errors:
        print(f"Completed with errors for: {errors}")
    else:
        print("All figures saved to results/figures/:")
        print("  forest_plot.png, shrinkage_plot.png, ppc_plot.png")
        print("  figure_S1_trace_rhat.png (Supplementary)")
        print("  figure_2a_ppc_pooled.png, figure_2b_ppc_by_measure.png")
        print("  figure_4_sensitivity_forest.png (Figure 4 — prior robustness)")
    print("=" * 65)
